/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre") 
    implementation("org.mongodb:mongodb-driver-sync:4.1.2")
    // implementation(files("/usr/local/Cellar/opencv/4.5.5_1/share/java/opencv4/opencv-455.jar"))
    implementation(files("C:/Users/Wael/Downloads/opencv/build/java/opencv-455.jar"))

    //embedded system jar-files
    //implementation(files("/Users/malinramkull/Desktop/jarfiles/arduino.jar"))
    //implementation(files("/Users/malinramkull/Desktop/jarfiles/jSerialComm-1.3.11.jar"))
}

application {
    // Define the main class for the application.
    mainClass.set("test.TestApp")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
