/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import java.io.IOException;

import server.misc.ShortcutFunctions;

public class App {

    public static void main(String[] args) throws InterruptedException {

        try {

            ShortcutFunctions.initializeOpencv();

            

        } catch (IOException e) {
            e.printStackTrace();
        }

    }

}
